// Work domain service — barrel. Reads degrade to empty; writes throw.
export { ensureWorkTables } from "./shared";
export {
  getOrCreateDefaultWorkspace,
  listAreas,
  listProjects,
  listPeople,
  listMeetings,
  listTasks,
  listNotes,
  getReview,
  getWorkTodaySnapshot,
  type WorkTodaySnapshot,
} from "./reads";
export {
  createArea,
  updateArea,
  createProject,
  updateProject,
  createWorkPerson,
  updateWorkPerson,
  createMeeting,
  updateMeeting,
  createTask,
  updateTask,
  setTaskDone,
  deleteTask,
  createNote,
  setNoteResolved,
  deleteNote,
  saveReview,
  type WorkAreaInput,
  type WorkProjectInput,
  type WorkPersonInput,
  type WorkMeetingInput,
  type WorkTaskInput,
  type WorkNoteInput,
  type WorkReviewInput,
} from "./mutations";
