// Work domain service — barrel. Reads degrade to empty; writes throw.
export { ensureWorkTables } from "./shared";
export {
  getOrCreateDefaultWorkspace,
  listAreas,
  listProjects,
  listPeople,
  listMeetings,
  listTasks,
  listNotes,
  getReview,
  getWorkTodaySnapshot,
  type WorkTodaySnapshot,
} from "./reads";
export {
  createArea,
  updateArea,
  createProject,
  updateProject,
  deleteWorkProject,
  createWorkPerson,
  updateWorkPerson,
  deleteWorkPerson,
  createMeeting,
  updateMeeting,
  createTask,
  updateTask,
  setTaskDone,
  deleteTask,
  createNote,
  setNoteResolved,
  deleteNote,
  saveReview,
  type WorkAreaInput,
  type WorkProjectInput,
  type WorkPersonInput,
  type WorkMeetingInput,
  type WorkTaskInput,
  type WorkNoteInput,
  type WorkReviewInput,
} from "./mutations";
export {
  // Orchestrators that route work objects through the owning tools.
  createWorkTask,
  updateWorkTask,
  setWorkTaskDone,
  deleteWorkTask,
  createWorkMeeting,
  updateWorkMeeting,
  archiveWorkMeeting,
  createCoworker,
  linkCoworker,
  createLinkedWorkProject,
  linkExistingProject,
  // Cross-surface reads for /app/do, /app/rolodex, /app/projects, assistant.
  listCoworkerCandidates,
  listUnlinkedProjectOptions,
  getWorkContextForDoItems,
  getWorkContextForRolodexPerson,
  getWorkspaceNamesByProjectId,
  getWorkAssistantSummary,
  type DoItemWorkContext,
  type RolodexWorkContext,
  type WorkAssistantSummary,
} from "./integrations";
